mkdir my_out
solutions\formularubens.exe < in\inFormularubens1.txt > my_out\outFormularubens1.txt
solutions\formularubens.exe < in\inFormularubens2.txt > my_out\outFormularubens2.txt
solutions\formularubens.exe < in\inFormularubens3.txt > my_out\outFormularubens3.txt
solutions\formularubens.exe < in\inFormularubens4.txt > my_out\outFormularubens4.txt
solutions\formularubens.exe < in\inFormularubens5.txt > my_out\outFormularubens5.txt
solutions\formularubens.exe < in\inFormularubens6.txt > my_out\outFormularubens6.txt
solutions\formularubens.exe < in\inFormularubens7.txt > my_out\outFormularubens7.txt
solutions\formularubens.exe < in\inFormularubens8.txt > my_out\outFormularubens8.txt
solutions\formularubens.exe < in\inFormularubens9.txt > my_out\outFormularubens9.txt
solutions\formularubens.exe < in\inFormularubens10.txt > my_out\outFormularubens10.txt
solutions\formularubens.exe < in\inFormularubens11.txt > my_out\outFormularubens11.txt
solutions\formularubens.exe < in\inFormularubens12.txt > my_out\outFormularubens12.txt
solutions\formularubens.exe < in\inFormularubens13.txt > my_out\outFormularubens13.txt
solutions\formularubens.exe < in\inFormularubens14.txt > my_out\outFormularubens14.txt
solutions\formularubens.exe < in\inFormularubens15.txt > my_out\outFormularubens15.txt
solutions\formularubens.exe < in\inFormularubens16.txt > my_out\outFormularubens16.txt
solutions\formularubens.exe < in\inFormularubens17.txt > my_out\outFormularubens17.txt
solutions\formularubens.exe < in\inFormularubens18.txt > my_out\outFormularubens18.txt
solutions\formularubens.exe < in\inFormularubens19.txt > my_out\outFormularubens19.txt
solutions\formularubens.exe < in\inFormularubens20.txt > my_out\outFormularubens20.txt
solutions\formularubens.exe < in\inFormularubens21.txt > my_out\outFormularubens21.txt
solutions\formularubens.exe < in\inFormularubens22.txt > my_out\outFormularubens22.txt
solutions\formularubens.exe < in\inFormularubens23.txt > my_out\outFormularubens23.txt
solutions\formularubens.exe < in\inFormularubens24.txt > my_out\outFormularubens24.txt
solutions\formularubens.exe < in\inFormularubens25.txt > my_out\outFormularubens25.txt
solutions\formularubens.exe < in\inFormularubens26.txt > my_out\outFormularubens26.txt
solutions\formularubens.exe < in\inFormularubens27.txt > my_out\outFormularubens27.txt
solutions\formularubens.exe < in\inFormularubens28.txt > my_out\outFormularubens28.txt
solutions\formularubens.exe < in\inFormularubens29.txt > my_out\outFormularubens29.txt
solutions\formularubens.exe < in\inFormularubens30.txt > my_out\outFormularubens30.txt
solutions\formularubens.exe < in\inFormularubens31.txt > my_out\outFormularubens31.txt
solutions\formularubens.exe < in\inFormularubens32.txt > my_out\outFormularubens32.txt
solutions\formularubens.exe < in\inFormularubens33.txt > my_out\outFormularubens33.txt
solutions\formularubens.exe < in\inFormularubens34.txt > my_out\outFormularubens34.txt
solutions\formularubens.exe < in\inFormularubens35.txt > my_out\outFormularubens35.txt
solutions\formularubens.exe < in\inFormularubens36.txt > my_out\outFormularubens36.txt
solutions\formularubens.exe < in\inFormularubens37.txt > my_out\outFormularubens37.txt
solutions\formularubens.exe < in\inFormularubens38.txt > my_out\outFormularubens38.txt
solutions\formularubens.exe < in\inFormularubens39.txt > my_out\outFormularubens39.txt
solutions\formularubens.exe < in\inFormularubens40.txt > my_out\outFormularubens40.txt
solutions\formularubens.exe < in\inFormularubens41.txt > my_out\outFormularubens41.txt
solutions\formularubens.exe < in\inFormularubens42.txt > my_out\outFormularubens42.txt
solutions\formularubens.exe < in\inFormularubens43.txt > my_out\outFormularubens43.txt
solutions\formularubens.exe < in\inFormularubens44.txt > my_out\outFormularubens44.txt
solutions\formularubens.exe < in\inFormularubens45.txt > my_out\outFormularubens45.txt
solutions\formularubens.exe < in\inFormularubens46.txt > my_out\outFormularubens46.txt
solutions\formularubens.exe < in\inFormularubens47.txt > my_out\outFormularubens47.txt
solutions\formularubens.exe < in\inFormularubens48.txt > my_out\outFormularubens48.txt
solutions\formularubens.exe < in\inFormularubens49.txt > my_out\outFormularubens49.txt
solutions\formularubens.exe < in\inFormularubens50.txt > my_out\outFormularubens50.txt
solutions\formularubens.exe < in\inFormularubens51.txt > my_out\outFormularubens51.txt
solutions\formularubens.exe < in\inFormularubens52.txt > my_out\outFormularubens52.txt
solutions\formularubens.exe < in\inFormularubens53.txt > my_out\outFormularubens53.txt
solutions\formularubens.exe < in\inFormularubens54.txt > my_out\outFormularubens54.txt
solutions\formularubens.exe < in\inFormularubens55.txt > my_out\outFormularubens55.txt
solutions\formularubens.exe < in\inFormularubens56.txt > my_out\outFormularubens56.txt
solutions\formularubens.exe < in\inFormularubens57.txt > my_out\outFormularubens57.txt
solutions\formularubens.exe < in\inFormularubens58.txt > my_out\outFormularubens58.txt
solutions\formularubens.exe < in\inFormularubens59.txt > my_out\outFormularubens59.txt
solutions\formularubens.exe < in\inFormularubens60.txt > my_out\outFormularubens60.txt
solutions\formularubens.exe < in\inFormularubens61.txt > my_out\outFormularubens61.txt
solutions\formularubens.exe < in\inFormularubens62.txt > my_out\outFormularubens62.txt
solutions\formularubens.exe < in\inFormularubens63.txt > my_out\outFormularubens63.txt
solutions\formularubens.exe < in\inFormularubens64.txt > my_out\outFormularubens64.txt
solutions\formularubens.exe < in\inFormularubens65.txt > my_out\outFormularubens65.txt
solutions\formularubens.exe < in\inFormularubens66.txt > my_out\outFormularubens66.txt
solutions\formularubens.exe < in\inFormularubens67.txt > my_out\outFormularubens67.txt
solutions\formularubens.exe < in\inFormularubens68.txt > my_out\outFormularubens68.txt
solutions\formularubens.exe < in\inFormularubens69.txt > my_out\outFormularubens69.txt
solutions\formularubens.exe < in\inFormularubens70.txt > my_out\outFormularubens70.txt
solutions\formularubens.exe < in\inFormularubens71.txt > my_out\outFormularubens71.txt
solutions\formularubens.exe < in\inFormularubens72.txt > my_out\outFormularubens72.txt
solutions\formularubens.exe < in\inFormularubens73.txt > my_out\outFormularubens73.txt
solutions\formularubens.exe < in\inFormularubens74.txt > my_out\outFormularubens74.txt
solutions\formularubens.exe < in\inFormularubens75.txt > my_out\outFormularubens75.txt
solutions\formularubens.exe < in\inFormularubens76.txt > my_out\outFormularubens76.txt
solutions\formularubens.exe < in\inFormularubens77.txt > my_out\outFormularubens77.txt
solutions\formularubens.exe < in\inFormularubens78.txt > my_out\outFormularubens78.txt
solutions\formularubens.exe < in\inFormularubens79.txt > my_out\outFormularubens79.txt
solutions\formularubens.exe < in\inFormularubens80.txt > my_out\outFormularubens80.txt
solutions\formularubens.exe < in\inFormularubens81.txt > my_out\outFormularubens81.txt
solutions\formularubens.exe < in\inFormularubens82.txt > my_out\outFormularubens82.txt
solutions\formularubens.exe < in\inFormularubens83.txt > my_out\outFormularubens83.txt
solutions\formularubens.exe < in\inFormularubens84.txt > my_out\outFormularubens84.txt
solutions\formularubens.exe < in\inFormularubens85.txt > my_out\outFormularubens85.txt
solutions\formularubens.exe < in\inFormularubens86.txt > my_out\outFormularubens86.txt
solutions\formularubens.exe < in\inFormularubens87.txt > my_out\outFormularubens87.txt
solutions\formularubens.exe < in\inFormularubens88.txt > my_out\outFormularubens88.txt
solutions\formularubens.exe < in\inFormularubens89.txt > my_out\outFormularubens89.txt
solutions\formularubens.exe < in\inFormularubens90.txt > my_out\outFormularubens90.txt
solutions\formularubens.exe < in\inFormularubens91.txt > my_out\outFormularubens91.txt
solutions\formularubens.exe < in\inFormularubens92.txt > my_out\outFormularubens92.txt
solutions\formularubens.exe < in\inFormularubens93.txt > my_out\outFormularubens93.txt
solutions\formularubens.exe < in\inFormularubens94.txt > my_out\outFormularubens94.txt
solutions\formularubens.exe < in\inFormularubens95.txt > my_out\outFormularubens95.txt
solutions\formularubens.exe < in\inFormularubens96.txt > my_out\outFormularubens96.txt
solutions\formularubens.exe < in\inFormularubens97.txt > my_out\outFormularubens97.txt
solutions\formularubens.exe < in\inFormularubens98.txt > my_out\outFormularubens98.txt
solutions\formularubens.exe < in\inFormularubens99.txt > my_out\outFormularubens99.txt
solutions\formularubens.exe < in\inFormularubens100.txt > my_out\outFormularubens100.txt
pause
fc /L my_out\* out\*
pause
