mkdir my_out
frequencia.exe < in\frequencia_1 > my_out\frequencia_1
frequencia.exe < in\frequencia_2 > my_out\frequencia_2
frequencia.exe < in\frequencia_3 > my_out\frequencia_3
frequencia.exe < in\frequencia_4 > my_out\frequencia_4
frequencia.exe < in\frequencia_5 > my_out\frequencia_5
frequencia.exe < in\frequencia_6 > my_out\frequencia_6
frequencia.exe < in\frequencia_7 > my_out\frequencia_7
frequencia.exe < in\frequencia_8 > my_out\frequencia_8
frequencia.exe < in\frequencia_9 > my_out\frequencia_9
frequencia.exe < in\frequencia_10 > my_out\frequencia_10
frequencia.exe < in\frequencia_11 > my_out\frequencia_11
frequencia.exe < in\frequencia_12 > my_out\frequencia_12
frequencia.exe < in\frequencia_13 > my_out\frequencia_13
frequencia.exe < in\frequencia_14 > my_out\frequencia_14
frequencia.exe < in\frequencia_15 > my_out\frequencia_15
frequencia.exe < in\frequencia_16 > my_out\frequencia_16
frequencia.exe < in\frequencia_17 > my_out\frequencia_17
frequencia.exe < in\frequencia_18 > my_out\frequencia_18
frequencia.exe < in\frequencia_19 > my_out\frequencia_19
frequencia.exe < in\frequencia_20 > my_out\frequencia_20
frequencia.exe < in\frequencia_21 > my_out\frequencia_21
frequencia.exe < in\frequencia_22 > my_out\frequencia_22
frequencia.exe < in\frequencia_23 > my_out\frequencia_23
frequencia.exe < in\frequencia_24 > my_out\frequencia_24
frequencia.exe < in\frequencia_25 > my_out\frequencia_25
frequencia.exe < in\frequencia_26 > my_out\frequencia_26
frequencia.exe < in\frequencia_27 > my_out\frequencia_27
frequencia.exe < in\frequencia_28 > my_out\frequencia_28
frequencia.exe < in\frequencia_29 > my_out\frequencia_29
frequencia.exe < in\frequencia_30 > my_out\frequencia_30
frequencia.exe < in\frequencia_31 > my_out\frequencia_31
frequencia.exe < in\frequencia_32 > my_out\frequencia_32
frequencia.exe < in\frequencia_33 > my_out\frequencia_33
frequencia.exe < in\frequencia_34 > my_out\frequencia_34
frequencia.exe < in\frequencia_35 > my_out\frequencia_35
frequencia.exe < in\frequencia_36 > my_out\frequencia_36
frequencia.exe < in\frequencia_37 > my_out\frequencia_37
frequencia.exe < in\frequencia_38 > my_out\frequencia_38
frequencia.exe < in\frequencia_39 > my_out\frequencia_39
frequencia.exe < in\frequencia_40 > my_out\frequencia_40
frequencia.exe < in\frequencia_41 > my_out\frequencia_41
frequencia.exe < in\frequencia_42 > my_out\frequencia_42
frequencia.exe < in\frequencia_43 > my_out\frequencia_43
frequencia.exe < in\frequencia_44 > my_out\frequencia_44
frequencia.exe < in\frequencia_45 > my_out\frequencia_45
frequencia.exe < in\frequencia_46 > my_out\frequencia_46
frequencia.exe < in\frequencia_47 > my_out\frequencia_47
frequencia.exe < in\frequencia_48 > my_out\frequencia_48
frequencia.exe < in\frequencia_49 > my_out\frequencia_49
frequencia.exe < in\frequencia_50 > my_out\frequencia_50
frequencia.exe < in\frequencia_51 > my_out\frequencia_51
frequencia.exe < in\frequencia_52 > my_out\frequencia_52
frequencia.exe < in\frequencia_53 > my_out\frequencia_53
frequencia.exe < in\frequencia_54 > my_out\frequencia_54
frequencia.exe < in\frequencia_55 > my_out\frequencia_55
frequencia.exe < in\frequencia_56 > my_out\frequencia_56
frequencia.exe < in\frequencia_57 > my_out\frequencia_57
frequencia.exe < in\frequencia_58 > my_out\frequencia_58
frequencia.exe < in\frequencia_59 > my_out\frequencia_59
frequencia.exe < in\frequencia_60 > my_out\frequencia_60
frequencia.exe < in\frequencia_61 > my_out\frequencia_61
frequencia.exe < in\frequencia_62 > my_out\frequencia_62
frequencia.exe < in\frequencia_63 > my_out\frequencia_63
frequencia.exe < in\frequencia_64 > my_out\frequencia_64
frequencia.exe < in\frequencia_65 > my_out\frequencia_65
frequencia.exe < in\frequencia_66 > my_out\frequencia_66
frequencia.exe < in\frequencia_67 > my_out\frequencia_67
frequencia.exe < in\frequencia_68 > my_out\frequencia_68
frequencia.exe < in\frequencia_69 > my_out\frequencia_69
frequencia.exe < in\frequencia_70 > my_out\frequencia_70
frequencia.exe < in\frequencia_71 > my_out\frequencia_71
frequencia.exe < in\frequencia_72 > my_out\frequencia_72
frequencia.exe < in\frequencia_73 > my_out\frequencia_73
frequencia.exe < in\frequencia_74 > my_out\frequencia_74
frequencia.exe < in\frequencia_75 > my_out\frequencia_75
frequencia.exe < in\frequencia_76 > my_out\frequencia_76
frequencia.exe < in\frequencia_77 > my_out\frequencia_77
frequencia.exe < in\frequencia_78 > my_out\frequencia_78
frequencia.exe < in\frequencia_79 > my_out\frequencia_79
frequencia.exe < in\frequencia_80 > my_out\frequencia_80
frequencia.exe < in\frequencia_81 > my_out\frequencia_81
frequencia.exe < in\frequencia_82 > my_out\frequencia_82
frequencia.exe < in\frequencia_83 > my_out\frequencia_83
frequencia.exe < in\frequencia_84 > my_out\frequencia_84
frequencia.exe < in\frequencia_85 > my_out\frequencia_85
frequencia.exe < in\frequencia_86 > my_out\frequencia_86
frequencia.exe < in\frequencia_87 > my_out\frequencia_87
frequencia.exe < in\frequencia_88 > my_out\frequencia_88
frequencia.exe < in\frequencia_89 > my_out\frequencia_89
frequencia.exe < in\frequencia_90 > my_out\frequencia_90
frequencia.exe < in\frequencia_91 > my_out\frequencia_91
frequencia.exe < in\frequencia_92 > my_out\frequencia_92
frequencia.exe < in\frequencia_93 > my_out\frequencia_93
frequencia.exe < in\frequencia_94 > my_out\frequencia_94
frequencia.exe < in\frequencia_95 > my_out\frequencia_95
frequencia.exe < in\frequencia_96 > my_out\frequencia_96
frequencia.exe < in\frequencia_97 > my_out\frequencia_97
frequencia.exe < in\frequencia_98 > my_out\frequencia_98
frequencia.exe < in\frequencia_99 > my_out\frequencia_99
pause
fc /L my_out\* out\*
pause
