mkdir my_out
solutions\faith.exe < in\inFaith1.txt > my_out\outFaith1.txt
solutions\faith.exe < in\inFaith2.txt > my_out\outFaith2.txt
solutions\faith.exe < in\inFaith3.txt > my_out\outFaith3.txt
solutions\faith.exe < in\inFaith4.txt > my_out\outFaith4.txt
solutions\faith.exe < in\inFaith5.txt > my_out\outFaith5.txt
solutions\faith.exe < in\inFaith6.txt > my_out\outFaith6.txt
solutions\faith.exe < in\inFaith7.txt > my_out\outFaith7.txt
solutions\faith.exe < in\inFaith8.txt > my_out\outFaith8.txt
solutions\faith.exe < in\inFaith9.txt > my_out\outFaith9.txt
solutions\faith.exe < in\inFaith10.txt > my_out\outFaith10.txt
solutions\faith.exe < in\inFaith11.txt > my_out\outFaith11.txt
solutions\faith.exe < in\inFaith12.txt > my_out\outFaith12.txt
solutions\faith.exe < in\inFaith13.txt > my_out\outFaith13.txt
solutions\faith.exe < in\inFaith14.txt > my_out\outFaith14.txt
solutions\faith.exe < in\inFaith15.txt > my_out\outFaith15.txt
solutions\faith.exe < in\inFaith16.txt > my_out\outFaith16.txt
solutions\faith.exe < in\inFaith17.txt > my_out\outFaith17.txt
solutions\faith.exe < in\inFaith18.txt > my_out\outFaith18.txt
solutions\faith.exe < in\inFaith19.txt > my_out\outFaith19.txt
solutions\faith.exe < in\inFaith20.txt > my_out\outFaith20.txt
solutions\faith.exe < in\inFaith21.txt > my_out\outFaith21.txt
solutions\faith.exe < in\inFaith22.txt > my_out\outFaith22.txt
solutions\faith.exe < in\inFaith23.txt > my_out\outFaith23.txt
solutions\faith.exe < in\inFaith24.txt > my_out\outFaith24.txt
solutions\faith.exe < in\inFaith25.txt > my_out\outFaith25.txt
solutions\faith.exe < in\inFaith26.txt > my_out\outFaith26.txt
solutions\faith.exe < in\inFaith27.txt > my_out\outFaith27.txt
solutions\faith.exe < in\inFaith28.txt > my_out\outFaith28.txt
solutions\faith.exe < in\inFaith29.txt > my_out\outFaith29.txt
solutions\faith.exe < in\inFaith30.txt > my_out\outFaith30.txt
solutions\faith.exe < in\inFaith31.txt > my_out\outFaith31.txt
solutions\faith.exe < in\inFaith32.txt > my_out\outFaith32.txt
solutions\faith.exe < in\inFaith33.txt > my_out\outFaith33.txt
solutions\faith.exe < in\inFaith34.txt > my_out\outFaith34.txt
solutions\faith.exe < in\inFaith35.txt > my_out\outFaith35.txt
solutions\faith.exe < in\inFaith36.txt > my_out\outFaith36.txt
solutions\faith.exe < in\inFaith37.txt > my_out\outFaith37.txt
solutions\faith.exe < in\inFaith38.txt > my_out\outFaith38.txt
solutions\faith.exe < in\inFaith39.txt > my_out\outFaith39.txt
solutions\faith.exe < in\inFaith40.txt > my_out\outFaith40.txt
solutions\faith.exe < in\inFaith41.txt > my_out\outFaith41.txt
solutions\faith.exe < in\inFaith42.txt > my_out\outFaith42.txt
solutions\faith.exe < in\inFaith43.txt > my_out\outFaith43.txt
solutions\faith.exe < in\inFaith44.txt > my_out\outFaith44.txt
solutions\faith.exe < in\inFaith45.txt > my_out\outFaith45.txt
solutions\faith.exe < in\inFaith46.txt > my_out\outFaith46.txt
solutions\faith.exe < in\inFaith47.txt > my_out\outFaith47.txt
solutions\faith.exe < in\inFaith48.txt > my_out\outFaith48.txt
solutions\faith.exe < in\inFaith49.txt > my_out\outFaith49.txt
solutions\faith.exe < in\inFaith50.txt > my_out\outFaith50.txt
solutions\faith.exe < in\inFaith51.txt > my_out\outFaith51.txt
solutions\faith.exe < in\inFaith52.txt > my_out\outFaith52.txt
solutions\faith.exe < in\inFaith53.txt > my_out\outFaith53.txt
solutions\faith.exe < in\inFaith54.txt > my_out\outFaith54.txt
solutions\faith.exe < in\inFaith55.txt > my_out\outFaith55.txt
solutions\faith.exe < in\inFaith56.txt > my_out\outFaith56.txt
solutions\faith.exe < in\inFaith57.txt > my_out\outFaith57.txt
solutions\faith.exe < in\inFaith58.txt > my_out\outFaith58.txt
solutions\faith.exe < in\inFaith59.txt > my_out\outFaith59.txt
solutions\faith.exe < in\inFaith60.txt > my_out\outFaith60.txt
solutions\faith.exe < in\inFaith61.txt > my_out\outFaith61.txt
solutions\faith.exe < in\inFaith62.txt > my_out\outFaith62.txt
solutions\faith.exe < in\inFaith63.txt > my_out\outFaith63.txt
solutions\faith.exe < in\inFaith64.txt > my_out\outFaith64.txt
solutions\faith.exe < in\inFaith65.txt > my_out\outFaith65.txt
solutions\faith.exe < in\inFaith66.txt > my_out\outFaith66.txt
solutions\faith.exe < in\inFaith67.txt > my_out\outFaith67.txt
solutions\faith.exe < in\inFaith68.txt > my_out\outFaith68.txt
solutions\faith.exe < in\inFaith69.txt > my_out\outFaith69.txt
solutions\faith.exe < in\inFaith70.txt > my_out\outFaith70.txt
solutions\faith.exe < in\inFaith71.txt > my_out\outFaith71.txt
solutions\faith.exe < in\inFaith72.txt > my_out\outFaith72.txt
solutions\faith.exe < in\inFaith73.txt > my_out\outFaith73.txt
solutions\faith.exe < in\inFaith74.txt > my_out\outFaith74.txt
solutions\faith.exe < in\inFaith75.txt > my_out\outFaith75.txt
solutions\faith.exe < in\inFaith76.txt > my_out\outFaith76.txt
solutions\faith.exe < in\inFaith77.txt > my_out\outFaith77.txt
solutions\faith.exe < in\inFaith78.txt > my_out\outFaith78.txt
solutions\faith.exe < in\inFaith79.txt > my_out\outFaith79.txt
solutions\faith.exe < in\inFaith80.txt > my_out\outFaith80.txt
solutions\faith.exe < in\inFaith81.txt > my_out\outFaith81.txt
solutions\faith.exe < in\inFaith82.txt > my_out\outFaith82.txt
solutions\faith.exe < in\inFaith83.txt > my_out\outFaith83.txt
solutions\faith.exe < in\inFaith84.txt > my_out\outFaith84.txt
solutions\faith.exe < in\inFaith85.txt > my_out\outFaith85.txt
solutions\faith.exe < in\inFaith86.txt > my_out\outFaith86.txt
solutions\faith.exe < in\inFaith87.txt > my_out\outFaith87.txt
solutions\faith.exe < in\inFaith88.txt > my_out\outFaith88.txt
solutions\faith.exe < in\inFaith89.txt > my_out\outFaith89.txt
solutions\faith.exe < in\inFaith90.txt > my_out\outFaith90.txt
solutions\faith.exe < in\inFaith91.txt > my_out\outFaith91.txt
solutions\faith.exe < in\inFaith92.txt > my_out\outFaith92.txt
solutions\faith.exe < in\inFaith93.txt > my_out\outFaith93.txt
solutions\faith.exe < in\inFaith94.txt > my_out\outFaith94.txt
solutions\faith.exe < in\inFaith95.txt > my_out\outFaith95.txt
solutions\faith.exe < in\inFaith96.txt > my_out\outFaith96.txt
solutions\faith.exe < in\inFaith97.txt > my_out\outFaith97.txt
solutions\faith.exe < in\inFaith98.txt > my_out\outFaith98.txt
solutions\faith.exe < in\inFaith99.txt > my_out\outFaith99.txt
solutions\faith.exe < in\inFaith100.txt > my_out\outFaith100.txt
pause
fc /L my_out\* out\*
pause
