mkdir my_out
bingo.exe < in\bingo_1 > my_out\bingo_1
bingo.exe < in\bingo_2 > my_out\bingo_2
bingo.exe < in\bingo_3 > my_out\bingo_3
bingo.exe < in\bingo_4 > my_out\bingo_4
bingo.exe < in\bingo_5 > my_out\bingo_5
bingo.exe < in\bingo_6 > my_out\bingo_6
bingo.exe < in\bingo_7 > my_out\bingo_7
bingo.exe < in\bingo_8 > my_out\bingo_8
bingo.exe < in\bingo_9 > my_out\bingo_9
bingo.exe < in\bingo_10 > my_out\bingo_10
bingo.exe < in\bingo_11 > my_out\bingo_11
bingo.exe < in\bingo_12 > my_out\bingo_12
bingo.exe < in\bingo_13 > my_out\bingo_13
bingo.exe < in\bingo_14 > my_out\bingo_14
bingo.exe < in\bingo_15 > my_out\bingo_15
bingo.exe < in\bingo_16 > my_out\bingo_16
bingo.exe < in\bingo_17 > my_out\bingo_17
bingo.exe < in\bingo_18 > my_out\bingo_18
bingo.exe < in\bingo_19 > my_out\bingo_19
bingo.exe < in\bingo_20 > my_out\bingo_20
bingo.exe < in\bingo_21 > my_out\bingo_21
bingo.exe < in\bingo_22 > my_out\bingo_22
bingo.exe < in\bingo_23 > my_out\bingo_23
bingo.exe < in\bingo_24 > my_out\bingo_24
bingo.exe < in\bingo_25 > my_out\bingo_25
bingo.exe < in\bingo_26 > my_out\bingo_26
bingo.exe < in\bingo_27 > my_out\bingo_27
bingo.exe < in\bingo_28 > my_out\bingo_28
bingo.exe < in\bingo_29 > my_out\bingo_29
bingo.exe < in\bingo_30 > my_out\bingo_30
bingo.exe < in\bingo_31 > my_out\bingo_31
bingo.exe < in\bingo_32 > my_out\bingo_32
bingo.exe < in\bingo_33 > my_out\bingo_33
bingo.exe < in\bingo_34 > my_out\bingo_34
bingo.exe < in\bingo_35 > my_out\bingo_35
bingo.exe < in\bingo_36 > my_out\bingo_36
bingo.exe < in\bingo_37 > my_out\bingo_37
bingo.exe < in\bingo_38 > my_out\bingo_38
bingo.exe < in\bingo_39 > my_out\bingo_39
bingo.exe < in\bingo_40 > my_out\bingo_40
bingo.exe < in\bingo_41 > my_out\bingo_41
bingo.exe < in\bingo_42 > my_out\bingo_42
bingo.exe < in\bingo_43 > my_out\bingo_43
bingo.exe < in\bingo_44 > my_out\bingo_44
bingo.exe < in\bingo_45 > my_out\bingo_45
bingo.exe < in\bingo_46 > my_out\bingo_46
bingo.exe < in\bingo_47 > my_out\bingo_47
bingo.exe < in\bingo_48 > my_out\bingo_48
bingo.exe < in\bingo_49 > my_out\bingo_49
bingo.exe < in\bingo_50 > my_out\bingo_50
bingo.exe < in\bingo_51 > my_out\bingo_51
bingo.exe < in\bingo_52 > my_out\bingo_52
bingo.exe < in\bingo_53 > my_out\bingo_53
bingo.exe < in\bingo_54 > my_out\bingo_54
pause
fc /L my_out\* out\*
pause
